services:
    kasimi.mchaticonsmenu.listener:
        class: 'kasimi\mchaticonsmenu\event\listener'
        arguments:
            - '@language'
            - '@template'
            - '@?dmzx.mchat.settings'
        tags:
            - { name: 'event.listener' }
