services:
  mdaszuta.topicsearch.ajax_search:
    class: mdaszuta\topicsearch\controller\ajax_search
    arguments:
      - '@dbal.conn'
      - '@request'
      - '@user'
      - '@auth'
      - '@cache.driver'

  mdaszuta.topicsearch.event.listener:
    class: mdaszuta\topicsearch\event\main_listener
    arguments:
      - '@template'
      - '%core.root_path%'
      - '@controller.helper'
      - '@config'
    tags:
      - { name: event.listener }