paul999_ajaxshoutbox_post:
    path: /ajaxshoutbox/post
    defaults: { _controller: paul999.ajaxshoutbox.controller:post }

paul999_ajaxshoutbox_get_all:
    path: /ajaxshoutbox/getAll
    defaults: { _controller: paul999.ajaxshoutbox.controller:getAll }
paul999_ajaxshoutbox_get_after:
    path: /ajaxshoutbox/getAfter/{id}
    defaults: { _controller: paul999.ajaxshoutbox.controller:getAfter }
paul999_ajaxshoutbox_get_before:
    path: /ajaxshoutbox/getBefore/{id}
    defaults: { _controller: paul999.ajaxshoutbox.controller:getBefore }

paul999_ajaxshoutbox_validate_connect:
    path: /ajaxshoutbox/validate/{id}
    defaults: { _controller: paul999.ajaxshoutbox.controller:validate }

paul999_ajaxshoutbox_delete:
    path: /ajaxshoutbox/delete
    defaults: { _controller: paul999.ajaxshoutbox.controller:delete }
