lotusjeff_sitemap_sitemapindex:
    path: /sitemap/sitemap.xml
    defaults: { _controller: lotusjeff.sitemap.sitemap:index }
lotusjeff_sitemap_current:
    path: /sitemap/current.xml
    defaults: { _controller: lotusjeff.sitemap.sitemap:current }
lotusjeff_sitemap_topics:
    path: /sitemap/topics-{id}.xml
    defaults: { _controller: lotusjeff.sitemap.sitemap:topics }
lotusjeff_sitemap_forums:
    path: /sitemap/forums-{id}.xml
    defaults: { _controller: lotusjeff.sitemap.sitemap:forums }
lotusjeff_sitemap_additional:
    path: /sitemap/additional.xml
    defaults: { _controller: lotusjeff.sitemap.sitemap:additional }
