services:
    rmcgirr83.topfive.topfive:
        class: rmcgirr83\topfive\core\topfive
        arguments:
            - '@auth'
            - '@config'
            - '@cache'
            - '@content.visibility'
            - '@dbal.conn'
            - '@dispatcher'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    rmcgirr83.topfive.listener:
        class: rmcgirr83\topfive\event\listener
        arguments:
            - '@rmcgirr83.topfive.topfive'
            - '@config'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@?phpbb.collapsiblecategories.operator'
        tags:
            - { name: event.listener }
