services:
    rmcgirr83.elonw.listener:
        class: rmcgirr83\elonw\event\listener
        arguments:
            - '@language'
            - '@request'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
